### ISSUE TITLE
Add support to python 3

### ISSUE THREAD

**Issue by maxiplux** [dsc/bunch#48] opened 2018-02-05 13:41 UTC
My friend thanks for this amazing library , but please would be possible add support to python 3.
I think that is only change iteritems by items() , return Bunch( (k, bunchify(v)) for k,v in items(x) ) .
thanks

**Comment by jaraco** [comment] 2018-10-30 17:58
Dupe of #17

**Comment by dachshund-digital** [comment] 2021-07-19 14:23
Come on... Python2 is DEAD, not supporting Python3, really?

**Comment by mnaielksu1** [comment] 2024-02-16 17:30
I did the following changes in ```/python3.8/site-packages/bunch/__init__.py``` to support Python3:
Line 245:  ```return Bunch( (k, bunchify(v)) for k,v in x.items() )```  
Line 270:  ```return dict( (k, unbunchify(v)) for k,v in x.items() )```

Now ```from bunch import bunchify``` is working.

**Closed** 2024-09-20 07:09 UTC
